import { useTheme } from '@/contexts/ThemeContext';

export function useThemeColors() {
  const { currentTheme } = useTheme();

  // Provide fallback values if currentTheme is null
  if (!currentTheme) {
    return {
      // Default light theme colors
      background: 'hsl(0 0% 100%)',
      foreground: 'hsl(0 0% 3.9%)',
      card: 'hsl(0 0% 98%)',
      cardForeground: 'hsl(0 0% 3.9%)',
      popover: 'hsl(0 0% 100%)',
      popoverForeground: 'hsl(0 0% 3.9%)',
      primary: 'hsl(0 0% 9%)',
      primaryForeground: 'hsl(0 0% 98%)',
      secondary: 'hsl(0 0% 96.1%)',
      secondaryForeground: 'hsl(0 0% 9%)',
      muted: 'hsl(0 0% 96.1%)',
      mutedForeground: 'hsl(0 0% 45.1%)',
      accent: 'hsl(0 0% 96.1%)',
      accentForeground: 'hsl(0 0% 9%)',
      destructive: 'hsl(0 84.2% 60.2%)',
      destructiveForeground: 'hsl(0 0% 98%)',
      border: 'hsl(0 0% 89.8%)',
      input: 'hsl(0 0% 96.1%)',
      ring: 'hsl(0 0% 3.9%)',
      chart1: 'hsl(12 76% 61%)',
      chart2: 'hsl(173 58% 39%)',
      chart3: 'hsl(197 37% 24%)',
      chart4: 'hsl(43 74% 66%)',
      chart5: 'hsl(27 87% 67%)',

      // Raw HSL values for use with opacity
      backgroundHsl: '0 0% 100%',
      foregroundHsl: '0 0% 3.9%',
      primaryHsl: '0 0% 9%',
      secondaryHsl: '0 0% 96.1%',
      accentHsl: '0 0% 96.1%',
      destructiveHsl: '0 84.2% 60.2%',

      // Font families
      fonts: {
        sans: 'Inter, system-ui, sans-serif',
        serif: 'Georgia, serif',
        mono: 'Courier New, Monaco, Consolas, monospace',
        heading: 'Inter, system-ui, sans-serif',
        body: 'Inter, system-ui, sans-serif',
      },

      // Button configurations (fallback to defaults)
      buttons: {
        default: {
          background: 'hsl(0 0% 9%)',
          color: 'hsl(0 0% 98%)',
          border: 'none',
          borderStyle: 'solid',
          borderWidth: '0',
          borderColor: 'transparent',
          borderRadius: '0.375rem',
          boxShadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
          hover: {
            background: 'hsl(0 0% 9% / 0.9)',
            color: 'hsl(0 0% 98%)',
            transform: 'none',
            borderStyle: 'solid',
            borderColor: 'transparent',
            boxShadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
          },
          active: {
            background: 'hsl(0 0% 9% / 0.8)',
            color: 'hsl(0 0% 98%)',
            transform: 'none',
            borderStyle: 'solid',
            borderColor: 'transparent',
            boxShadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
          },
        },
        outline: {
          background: 'transparent',
          color: 'hsl(0 0% 3.9%)',
          border: '1px solid hsl(0 0% 89.8%)',
          borderStyle: 'solid',
          borderWidth: '1px',
          borderColor: 'hsl(0 0% 89.8%)',
          borderRadius: '0.375rem',
          boxShadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
          hover: {
            background: 'hsl(0 0% 96.1%)',
            color: 'hsl(0 0% 9%)',
            transform: 'none',
            borderStyle: 'solid',
            borderColor: 'hsl(0 0% 89.8%)',
            boxShadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
          },
          active: {
            background: 'hsl(0 0% 96.1% / 0.8)',
            color: 'hsl(0 0% 9%)',
            transform: 'none',
            borderStyle: 'solid',
            borderColor: 'hsl(0 0% 89.8%)',
            boxShadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
          },
        },
        secondary: {
          background: 'hsl(0 0% 96.1%)',
          color: 'hsl(0 0% 9%)',
          border: 'none',
          borderStyle: 'solid',
          borderWidth: '0',
          borderColor: 'transparent',
          borderRadius: '0.375rem',
          boxShadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
          hover: {
            background: 'hsl(0 0% 96.1% / 0.8)',
            color: 'hsl(0 0% 9%)',
            transform: 'none',
            borderStyle: 'solid',
            borderColor: 'transparent',
            boxShadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
          },
          active: {
            background: 'hsl(0 0% 96.1% / 0.6)',
            color: 'hsl(0 0% 9%)',
            transform: 'none',
            borderStyle: 'solid',
            borderColor: 'transparent',
            boxShadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
          },
        },
        destructive: {
          background: 'hsl(0 84.2% 60.2%)',
          color: 'hsl(0 0% 98%)',
          border: 'none',
          borderStyle: 'solid',
          borderWidth: '0',
          borderColor: 'transparent',
          borderRadius: '0.375rem',
          boxShadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
          hover: {
            background: 'hsl(0 84.2% 60.2% / 0.9)',
            color: 'hsl(0 0% 98%)',
            transform: 'none',
            borderStyle: 'solid',
            borderColor: 'transparent',
            boxShadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
          },
          active: {
            background: 'hsl(0 84.2% 60.2% / 0.8)',
            color: 'hsl(0 0% 98%)',
            transform: 'none',
            borderStyle: 'solid',
            borderColor: 'transparent',
            boxShadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
          },
        },
        ghost: {
          background: 'transparent',
          color: 'hsl(0 0% 3.9%)',
          border: 'none',
          borderStyle: 'solid',
          borderWidth: '0',
          borderColor: 'transparent',
          borderRadius: '0.375rem',
          boxShadow: 'none',
          hover: {
            background: 'hsl(0 0% 96.1%)',
            color: 'hsl(0 0% 9%)',
            transform: 'none',
            borderStyle: 'solid',
            borderColor: 'transparent',
            boxShadow: 'none',
          },
          active: {
            background: 'hsl(0 0% 96.1% / 0.8)',
            color: 'hsl(0 0% 9%)',
            transform: 'none',
            borderStyle: 'solid',
            borderColor: 'transparent',
            boxShadow: 'none',
          },
        },
        link: {
          background: 'transparent',
          color: 'hsl(0 0% 9%)',
          border: 'none',
          borderStyle: 'solid',
          borderWidth: '0',
          borderColor: 'transparent',
          borderRadius: '0',
          boxShadow: 'none',
          hover: {
            background: 'transparent',
            color: 'hsl(0 0% 9%)',
            transform: 'none',
            borderStyle: 'solid',
            borderColor: 'transparent',
            boxShadow: 'none',
          },
          active: {
            background: 'transparent',
            color: 'hsl(0 0% 9%)',
            transform: 'none',
            borderStyle: 'solid',
            borderColor: 'transparent',
            boxShadow: 'none',
          },
        },
      },
    };
  }

  return {
    // Convert HSL values to CSS color strings
    background: `hsl(${currentTheme.colors.background})`,
    foreground: `hsl(${currentTheme.colors.foreground})`,
    card: `hsl(${currentTheme.colors.card})`,
    cardForeground: `hsl(${currentTheme.colors.cardForeground})`,
    popover: `hsl(${currentTheme.colors.popover})`,
    popoverForeground: `hsl(${currentTheme.colors.popoverForeground})`,
    primary: `hsl(${currentTheme.colors.primary})`,
    primaryForeground: `hsl(${currentTheme.colors.primaryForeground})`,
    secondary: `hsl(${currentTheme.colors.secondary})`,
    secondaryForeground: `hsl(${currentTheme.colors.secondaryForeground})`,
    muted: `hsl(${currentTheme.colors.muted})`,
    mutedForeground: `hsl(${currentTheme.colors.mutedForeground})`,
    accent: `hsl(${currentTheme.colors.accent})`,
    accentForeground: `hsl(${currentTheme.colors.accentForeground})`,
    destructive: `hsl(${currentTheme.colors.destructive})`,
    destructiveForeground: `hsl(${currentTheme.colors.destructiveForeground})`,
    border: `hsl(${currentTheme.colors.border})`,
    input: `hsl(${currentTheme.colors.input})`,
    ring: `hsl(${currentTheme.colors.ring})`,
    chart1: `hsl(${currentTheme.colors.chart1})`,
    chart2: `hsl(${currentTheme.colors.chart2})`,
    chart3: `hsl(${currentTheme.colors.chart3})`,
    chart4: `hsl(${currentTheme.colors.chart4})`,
    chart5: `hsl(${currentTheme.colors.chart5})`,

    // Raw HSL values for use with opacity
    backgroundHsl: currentTheme.colors.background,
    foregroundHsl: currentTheme.colors.foreground,
    primaryHsl: currentTheme.colors.primary,
    secondaryHsl: currentTheme.colors.secondary,
    accentHsl: currentTheme.colors.accent,
    destructiveHsl: currentTheme.colors.destructive,

    // Font families
    fonts: currentTheme.fonts,

    // Button configurations with fallbacks to theme defaults
    buttons: {
      default: {
        background: currentTheme.buttons?.default?.background || `hsl(${currentTheme.colors.primary})`,
        color: currentTheme.buttons?.default?.color || `hsl(${currentTheme.colors.primaryForeground})`,
        border: currentTheme.buttons?.default?.border || 'none',
        borderStyle: currentTheme.buttons?.default?.borderStyle || 'solid',
        borderWidth: currentTheme.buttons?.default?.borderWidth || '0',
        borderColor: currentTheme.buttons?.default?.borderColor || 'transparent',
        borderRadius: currentTheme.buttons?.default?.borderRadius || currentTheme.corners.md,
        boxShadow: currentTheme.buttons?.default?.boxShadow || currentTheme.shadows.button,
        hover: currentTheme.buttons?.default?.hover,
        active: currentTheme.buttons?.default?.active,
      },
      outline: {
        background: currentTheme.buttons?.outline?.background || 'transparent',
        color: currentTheme.buttons?.outline?.color || `hsl(${currentTheme.colors.foreground})`,
        border: currentTheme.buttons?.outline?.border || `1px solid hsl(${currentTheme.colors.border})`,
        borderStyle: currentTheme.buttons?.outline?.borderStyle || 'solid',
        borderWidth: currentTheme.buttons?.outline?.borderWidth || '1px',
        borderColor: currentTheme.buttons?.outline?.borderColor || `hsl(${currentTheme.colors.border})`,
        borderRadius: currentTheme.buttons?.outline?.borderRadius || currentTheme.corners.md,
        boxShadow: currentTheme.buttons?.outline?.boxShadow || currentTheme.shadows.button,
        hover: currentTheme.buttons?.outline?.hover,
        active: currentTheme.buttons?.outline?.active,
      },
      secondary: {
        background: currentTheme.buttons?.secondary?.background || `hsl(${currentTheme.colors.secondary})`,
        color: currentTheme.buttons?.secondary?.color || `hsl(${currentTheme.colors.secondaryForeground})`,
        border: currentTheme.buttons?.secondary?.border || 'none',
        borderStyle: currentTheme.buttons?.secondary?.borderStyle || 'solid',
        borderWidth: currentTheme.buttons?.secondary?.borderWidth || '0',
        borderColor: currentTheme.buttons?.secondary?.borderColor || 'transparent',
        borderRadius: currentTheme.buttons?.secondary?.borderRadius || currentTheme.corners.md,
        boxShadow: currentTheme.buttons?.secondary?.boxShadow || currentTheme.shadows.button,
        hover: currentTheme.buttons?.secondary?.hover,
        active: currentTheme.buttons?.secondary?.active,
      },
      destructive: {
        background: currentTheme.buttons?.destructive?.background || `hsl(${currentTheme.colors.destructive})`,
        color: currentTheme.buttons?.destructive?.color || `hsl(${currentTheme.colors.destructiveForeground})`,
        border: currentTheme.buttons?.destructive?.border || 'none',
        borderStyle: currentTheme.buttons?.destructive?.borderStyle || 'solid',
        borderWidth: currentTheme.buttons?.destructive?.borderWidth || '0',
        borderColor: currentTheme.buttons?.destructive?.borderColor || 'transparent',
        borderRadius: currentTheme.buttons?.destructive?.borderRadius || currentTheme.corners.md,
        boxShadow: currentTheme.buttons?.destructive?.boxShadow || currentTheme.shadows.button,
        hover: currentTheme.buttons?.destructive?.hover,
        active: currentTheme.buttons?.destructive?.active,
      },
      ghost: {
        background: currentTheme.buttons?.ghost?.background || 'transparent',
        color: currentTheme.buttons?.ghost?.color || `hsl(${currentTheme.colors.foreground})`,
        border: currentTheme.buttons?.ghost?.border || 'none',
        borderStyle: currentTheme.buttons?.ghost?.borderStyle || 'solid',
        borderWidth: currentTheme.buttons?.ghost?.borderWidth || '0',
        borderColor: currentTheme.buttons?.ghost?.borderColor || 'transparent',
        borderRadius: currentTheme.buttons?.ghost?.borderRadius || currentTheme.corners.md,
        boxShadow: currentTheme.buttons?.ghost?.boxShadow || 'none',
        hover: currentTheme.buttons?.ghost?.hover,
        active: currentTheme.buttons?.ghost?.active,
      },
      link: {
        background: currentTheme.buttons?.link?.background || 'transparent',
        color: currentTheme.buttons?.link?.color || `hsl(${currentTheme.colors.primary})`,
        border: currentTheme.buttons?.link?.border || 'none',
        borderStyle: currentTheme.buttons?.link?.borderStyle || 'solid',
        borderWidth: currentTheme.buttons?.link?.borderWidth || '0',
        borderColor: currentTheme.buttons?.link?.borderColor || 'transparent',
        borderRadius: currentTheme.buttons?.link?.borderRadius || '0',
        boxShadow: currentTheme.buttons?.link?.boxShadow || 'none',
        hover: currentTheme.buttons?.link?.hover,
        active: currentTheme.buttons?.link?.active,
      },
    },
  };
}
