[package]
name = "sage-apps"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
sage = { workspace = true }
sage-api = { workspace = true, features = ["tauri"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
specta = { workspace = true, features = ["derive", "function", "url"] }
specta-typescript = { workspace = true }
tauri = { workspace = true, features = ["macos-private-api"] }
tauri-plugin-dialog = "2.7.1"
tauri-plugin-opener = { workspace = true }
tokio = { workspace = true, features = ["net"] }
tracing = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
anyhow = { workspace = true }
semver = { workspace = true }
hex = { workspace = true }
sqlx = { workspace = true, features = ["sqlite", "runtime-tokio"] }
sha2 = "0.10.9"
uuid = { version = "1.19.0", features = ["v4", "serde"] }
tempfile = "3"
zip = "8.5.1"
mime_guess = "2"
url = "2"
async-trait = "0.1.89"
erased-serde = "0.4.9"
serde_path_to_error = "0.1.20"
parking_lot = "0.12.5"
futures = "0.3.32"

[dev-dependencies]
tempfile = { workspace = true }
